/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/zeraora.glb 
Author: cujohj410 (https://sketchfab.com/cujohj410)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zeraora-dbc5414887894aa79dbf6cb0d0e3d41d
Title: Zeraora
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/zeraora.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['pm0888_00_Eye1_tga_png-material']} skeleton={nodes.Object_6.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['pm0888_00_BodyA1_tga_png-material']} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['pm0888_00_BodyB1_tga_png-material']} skeleton={nodes.Object_10.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/zeraora.glb')
